feat: UI data stubs
didx-xyz/ssi-trust-registry pull request #170
Opened 2023-12-01 09:28 UTC by andrii-uhryn-absa

2023-12-01 10:54 UTC, niall-shaw commented on packages/frontend/src/fixtures/stubs.ts
> +      dids: ['did:indy:sovrin:staging:C279iyCR8wtKiPC8o9iPmc'],
I think we should use a different entity, with different did (should be unique per entity), logo domain etc.
Even the id is the same!

2023-12-01 10:54 UTC, niall-shaw commented on packages/frontend/src/fixtures/stubs.ts
> +        'did:indy:sovrin:staging:C279iyCR8wtKiPC8o9iPmc/anoncreds/v0/SCHEMA/e-KYC/1.0.0',
Again, perhaps a different schema?

2023-12-01 10:54 UTC, niall-shaw commented on packages/frontend/src/fixtures/stubs.ts
> +    state: 'declined',
```suggestion
    state: 'rejected',
```
We don't have state `declined`

2023-12-01 10:54 UTC, niall-shaw commented on packages/frontend/src/fixtures/stubs.ts
> +]
I guess two of these should be associated with the existing entities, i.e. `entityId: ___`

2023-12-01 13:54 UTC, jakubkoci reviewed
It's good Andrii, just use a real data pls. Absa, Standard Bank, ... It helps to understand the system and relations.

2023-12-01 13:54 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +      name: 'Digital Identity 2',
We should use real data as much as possible. What about Phone Number or Bank Account credential?

2023-12-01 13:54 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +    name: 'John Doe',
This should be a company name, not a person.

2023-12-01 13:54 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +      name: 'Example entity',
No examples, real companies pls :)

2023-12-05 14:06 UTC, jakubkoci requested changes

2023-12-05 14:06 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +  ],
Could we pls add at least Standard Bank as a verifier here? Or DIDx, they should have some did on sovrin ledger 🤔

2023-12-05 14:06 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +    dids: ['did:key:z6MkjBWPPa1njEKygyr3LR3pRKkqv714vyTkfnUdP6ToFSH5'],
Is the `did:key` supported did? Is it resolveable by trust registry? 🤔

2023-12-06 15:20 UTC, jakubkoci requested changes

2023-12-06 15:20 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +      domain: 'https://didx.net',
This is wrong company

logo https://www.safbc.co.za/logos/didx.png
domain https://www.didx.co.za/

2023-12-12 14:42 UTC, jakubkoci requested changes

2023-12-12 14:42 UTC, jakubkoci commented on packages/frontend/src/fixtures/stubs.ts
> +    logo_url: 'https://didx.net/static/media/logo.d4f6a758.png',
Still wrong

2023-12-12 14:59 UTC, jakubkoci approved these changes

2023-12-12 15:00 UTC, merged